# Generated by Django 5.0.1 on 2024-02-13 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('title', models.CharField(unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(15)])),
                ('title_first_topic', models.CharField(validators=[django.core.validators.MinLengthValidator(3)])),
                ('description_first_topic', models.CharField(validators=[django.core.validators.MinLengthValidator(15)])),
                ('title_second_topic', models.CharField(validators=[django.core.validators.MinLengthValidator(3)])),
                ('description_second_topic', models.CharField(validators=[django.core.validators.MinLengthValidator(15)])),
                ('title_third_topic', models.CharField(validators=[django.core.validators.MinLengthValidator(3)])),
                ('description_third_topic', models.CharField(validators=[django.core.validators.MinLengthValidator(15)])),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
