# Generated by Django 5.0.3 on 2024-03-28 15:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(5)])),
                ('category', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snack', 'snack'), ('vegetarian', 'vegetarian'), ('vegan', 'vegan'), ('gluten-free', 'gluten-free'), ('dairy-free', 'dairy-free'), ('low-carb', 'low-carb'), ('low-calorie', 'low-calorie'), ('high-protein', 'high-protein'), ('pescatarian', 'pescatarian'), ('keto', 'keto'), ('paleo', 'paleo'), ('mediterranean', 'mediterranean'), ('whole30', 'whole30')], max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('ingredients', models.CharField()),
                ('prep_time', models.CharField()),
                ('cook_time', models.CharField()),
                ('servings', models.CharField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
