# Generated by Django 5.0.3 on 2024-03-28 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('', ''), ('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snack', 'snack'), ('vegetarian', 'vegetarian'), ('vegan', 'vegan'), ('gluten-free', 'gluten-free'), ('dairy-free', 'dairy-free'), ('low-carb', 'low-carb'), ('low-calorie', 'low-calorie'), ('high-protein', 'high-protein'), ('pescatarian', 'pescatarian'), ('keto', 'keto'), ('paleo', 'paleo'), ('mediterranean', 'mediterranean'), ('whole30', 'whole30')], max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
