# Generated by Django 4.2.2 on 2023-08-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
