# Generated by Django 4.2.2 on 2023-08-11 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0002_alter_initiative_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
