# Generated by Django 5.0.1 on 2024-01-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sushiuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email is not unique.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='sushiuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Username is not unique.'}, max_length=255, unique=True),
        ),
    ]
