# Generated by Django 5.0.1 on 2024-01-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_sushiuser_email_alter_sushiuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sushiuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='sushiuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='sushiuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='sushiuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sushiuser',
            name='is_staff',
        ),
    ]
