# Generated by Django 5.0.1 on 2024-01-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_sushiuser_is_active_sushiuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sushiuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='sushiuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sushiuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='sushiuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='sushiuser',
            name='user_permissions',
        ),
    ]
