# Generated by Django 4.2.2 on 2023-08-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creation_time',
        ),
    ]
