# Generated by Django 4.2.2 on 2023-09-28 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0004_alter_initiative_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativeregistration',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='initiatives.initiative'),
        ),
    ]
