# Generated by Django 4.2.2 on 2023-09-28 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0005_alter_initiativeregistration_initiative'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='initiativeregistration',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='initiativeregistration',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.initiative'),
        ),
    ]
