# Generated by Django 4.2.2 on 2023-09-28 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiatives', '0006_alter_initiativeregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
