import Ingredient from "../models/Ingredient.js";

export async function addDummyData() {
  const dummyData = [
    {
      ingredient: "Apple",
      breakdownInTheStomach: 2,
      smallIntestine: 3,
      fats: 0.3,
      carbohydrates: 14,
      protein: 0.3,
      grams: 100,
    },
    {
      ingredient: "Banana",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 0.3,
      carbohydrates: 23,
      protein: 1.1,
      grams: 100,
    },
    {
      ingredient: "Chicken Breast",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 1.5,
      carbohydrates: 0,
      protein: 31,
      grams: 100,
    },
    {
      ingredient: "Salmon",
      breakdownInTheStomach: 3.5,
      smallIntestine: 4.5,
      fats: 13,
      carbohydrates: 0,
      protein: 25,
      grams: 100,
    },
    {
      ingredient: "Broccoli",
      breakdownInTheStomach: 2,
      smallIntestine: 3,
      fats: 0.4,
      carbohydrates: 7,
      protein: 2.8,
      grams: 100,
    },
    {
      ingredient: "Beef Steak",
      breakdownInTheStomach: 4,
      smallIntestine: 5,
      fats: 15,
      carbohydrates: 0,
      protein: 26,
      grams: 100,
    },
    {
      ingredient: "Avocado",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 15,
      carbohydrates: 9,
      protein: 2,
      grams: 100,
    },
    {
      ingredient: "Almonds",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 49,
      carbohydrates: 22,
      protein: 21,
      grams: 100,
    },
    {
      ingredient: "Yogurt",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 3.3,
      carbohydrates: 4.7,
      protein: 10,
      grams: 100,
    },
    {
      ingredient: "Eggs",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 10,
      carbohydrates: 1.1,
      protein: 13,
      grams: 100,
    },
    {
      ingredient: "Bread",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 4,
      carbohydrates: 49,
      protein: 9,
      grams: 100,
    },
    {
      ingredient: "Rice",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 0.3,
      carbohydrates: 28,
      protein: 2.7,
      grams: 100,
    },
    {
      ingredient: "Pasta",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 1.1,
      carbohydrates: 31,
      protein: 5,
      grams: 100,
    },
    {
      ingredient: "Chicken Thigh",
      breakdownInTheStomach: 3.5,
      smallIntestine: 4.5,
      fats: 9,
      carbohydrates: 0,
      protein: 26,
      grams: 100,
    },
    {
      ingredient: "Pork Chop",
      breakdownInTheStomach: 4,
      smallIntestine: 5,
      fats: 15,
      carbohydrates: 0,
      protein: 27,
      grams: 100,
    },
    {
      ingredient: "Cheddar Cheese",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 33,
      carbohydrates: 1.3,
      protein: 25,
      grams: 100,
    },
    {
      ingredient: "Milk",
      breakdownInTheStomach: 2,
      smallIntestine: 3,
      fats: 1,
      carbohydrates: 5,
      protein: 3.4,
      grams: 100,
    },
    {
      ingredient: "Tuna",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 1,
      carbohydrates: 0,
      protein: 23,
      grams: 100,
    },
    {
      ingredient: "Ground Beef",
      breakdownInTheStomach: 4,
      smallIntestine: 5,
      fats: 15,
      carbohydrates: 0,
      protein: 26,
      grams: 100,
    },
    {
      ingredient: "Tofu",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 4.8,
      carbohydrates: 1.9,
      protein: 8,
      grams: 100,
    },
    {
      ingredient: "Spinach",
      breakdownInTheStomach: 2,
      smallIntestine: 3,
      fats: 0.4,
      carbohydrates: 3.6,
      protein: 2.9,
      grams: 100,
    },
    {
      ingredient: "Sweet Potato",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 0.1,
      carbohydrates: 20,
      protein: 1.6,
      grams: 100,
    },
    {
      ingredient: "Cauliflower",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 0.3,
      carbohydrates: 5,
      protein: 1.9,
      grams: 100,
    },
    {
      ingredient: "Tomato",
      breakdownInTheStomach: 2,
      smallIntestine: 3,
      fats: 0.2,
      carbohydrates: 3.9,
      protein: 0.9,
      grams: 100,
    },
    {
      ingredient: "Onion",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 0.1,
      carbohydrates: 9,
      protein: 1.1,
      grams: 100,
    },
    {
      ingredient: "Garlic",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 0.5,
      carbohydrates: 33,
      protein: 6.4,
      grams: 100,
    },
    {
      ingredient: "Chickpeas",
      breakdownInTheStomach: 3.5,
      smallIntestine: 4.5,
      fats: 6,
      carbohydrates: 27,
      protein: 9,
      grams: 100,
    },
    {
      ingredient: "Lentils",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 0.8,
      carbohydrates: 20,
      protein: 9,
      grams: 100,
    },
    {
      ingredient: "Quinoa",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 2.8,
      carbohydrates: 21,
      protein: 4.1,
      grams: 100,
    },
    {
      ingredient: "Oats",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 6.9,
      carbohydrates: 66,
      protein: 16.9,
      grams: 100,
    },
    {
      ingredient: "Cottage Cheese",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 4.3,
      carbohydrates: 3.4,
      protein: 11,
      grams: 100,
    },
    {
      ingredient: "Greek Yogurt",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 10,
      carbohydrates: 4,
      protein: 10,
      grams: 100,
    },
    {
      ingredient: "Pita Bread",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 1.5,
      carbohydrates: 55,
      protein: 6,
      grams: 100,
    },
    {
      ingredient: "Tortilla",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 7,
      carbohydrates: 46,
      protein: 8,
      grams: 100,
    },
    {
      ingredient: "Bagel",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 1.5,
      carbohydrates: 56,
      protein: 9,
      grams: 100,
    },
    {
      ingredient: "Muffin",
      breakdownInTheStomach: 3.5,
      smallIntestine: 4.5,
      fats: 14,
      carbohydrates: 53,
      protein: 6,
      grams: 100,
    },
    {
      ingredient: "Croissant",
      breakdownInTheStomach: 3.5,
      smallIntestine: 4.5,
      fats: 20,
      carbohydrates: 49,
      protein: 8,
      grams: 100,
    },
    {
      ingredient: "Pancakes",
      breakdownInTheStomach: 3.5,
      smallIntestine: 4.5,
      fats: 9,
      carbohydrates: 36,
      protein: 7,
      grams: 100,
    },
    {
      ingredient: "Waffles",
      breakdownInTheStomach: 3.5,
      smallIntestine: 4.5,
      fats: 12,
      carbohydrates: 45,
      protein: 6,
      grams: 100,
    },
    {
      ingredient: "Pizza",
      breakdownInTheStomach: 4,
      smallIntestine: 5,
      fats: 11,
      carbohydrates: 36,
      protein: 11,
      grams: 100,
    },
    {
      ingredient: "Hamburger",
      breakdownInTheStomach: 4,
      smallIntestine: 5,
      fats: 16,
      carbohydrates: 31,
      protein: 12,
      grams: 100,
    },
    {
      ingredient: "Hot Dog",
      breakdownInTheStomach: 4,
      smallIntestine: 5,
      fats: 14,
      carbohydrates: 2,
      protein: 10,
      grams: 100,
    },
    {
      ingredient: "Fried Chicken",
      breakdownInTheStomach: 4,
      smallIntestine: 5,
      fats: 14,
      carbohydrates: 10,
      protein: 14,
      grams: 100,
    },
    {
      ingredient: "Chicken Nuggets",
      breakdownInTheStomach: 4,
      smallIntestine: 5,
      fats: 15,
      carbohydrates: 22,
      protein: 12,
      grams: 100,
    },
    {
      ingredient: "French Fries",
      breakdownInTheStomach: 4,
      smallIntestine: 5,
      fats: 15,
      carbohydrates: 41,
      protein: 3,
      grams: 100,
    },
    {
      ingredient: "Potato Chips",
      breakdownInTheStomach: 4,
      smallIntestine: 5,
      fats: 30,
      carbohydrates: 52,
      protein: 6,
      grams: 100,
    },
    {
      ingredient: "Ice Cream",
      breakdownInTheStomach: 3.5,
      smallIntestine: 4.5,
      fats: 11,
      carbohydrates: 24,
      protein: 3,
      grams: 100,
    },
    {
      ingredient: "Cake",
      breakdownInTheStomach: 3.5,
      smallIntestine: 4.5,
      fats: 16,
      carbohydrates: 47,
      protein: 4,
      grams: 100,
    },
    {
      ingredient: "Cookies",
      breakdownInTheStomach: 3.5,
      smallIntestine: 4.5,
      fats: 19,
      carbohydrates: 63,
      protein: 6,
      grams: 100,
    },
    {
      ingredient: "Donuts",
      breakdownInTheStomach: 3.5,
      smallIntestine: 4.5,
      fats: 22,
      carbohydrates: 54,
      protein: 5,
      grams: 100,
    },
    {
      ingredient: "Brownies",
      breakdownInTheStomach: 3.5,
      smallIntestine: 4.5,
      fats: 17,
      carbohydrates: 62,
      protein: 4,
      grams: 100,
    },
    {
      ingredient: "Pie",
      breakdownInTheStomach: 3.5,
      smallIntestine: 4.5,
      fats: 18,
      carbohydrates: 50,
      protein: 3,
      grams: 100,
    },
    {
      ingredient: "Muesli",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 6,
      carbohydrates: 60,
      protein: 11,
      grams: 100,
    },
    {
      ingredient: "Granola",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 15,
      carbohydrates: 65,
      protein: 10,
      grams: 100,
    },
    {
      ingredient: "Chia Seeds",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 31,
      carbohydrates: 42,
      protein: 17,
      grams: 100,
    },
    {
      ingredient: "Flax Seeds",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 42,
      carbohydrates: 29,
      protein: 18,
      grams: 100,
    },
    {
      ingredient: "Pumpkin Seeds",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 19,
      carbohydrates: 4,
      protein: 30,
      grams: 100,
    },
    {
      ingredient: "Sunflower Seeds",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 51,
      carbohydrates: 20,
      protein: 21,
      grams: 100,
    },
    {
      ingredient: "Sesame Seeds",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 50,
      carbohydrates: 23,
      protein: 18,
      grams: 100,
    },
    {
      ingredient: "Pecans",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 72,
      carbohydrates: 14,
      protein: 9,
      grams: 100,
    },
    {
      ingredient: "Walnuts",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 65,
      carbohydrates: 14,
      protein: 15,
      grams: 100,
    },
    {
      ingredient: "Cashews",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 44,
      carbohydrates: 30,
      protein: 18,
      grams: 100,
    },
    {
      ingredient: "Macadamia Nuts",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 76,
      carbohydrates: 14,
      protein: 8,
      grams: 100,
    },
    {
      ingredient: "Hazelnuts",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 61,
      carbohydrates: 17,
      protein: 15,
      grams: 100,
    },
    {
      ingredient: "Pistachios",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 45,
      carbohydrates: 28,
      protein: 20,
      grams: 100,
    },
    {
      ingredient: "Peanuts",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 49,
      carbohydrates: 16,
      protein: 26,
      grams: 100,
    },
    {
      ingredient: "Hummus",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 8,
      carbohydrates: 16,
      protein: 8,
      grams: 100,
    },
    {
      ingredient: "Guacamole",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 15,
      carbohydrates: 9,
      protein: 2,
      grams: 100,
    },
    {
      ingredient: "Salsa",
      breakdownInTheStomach: 2,
      smallIntestine: 3,
      fats: 0.2,
      carbohydrates: 5,
      protein: 1,
      grams: 100,
    },
    {
      ingredient: "Poppy Seeds",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 49,
      carbohydrates: 28,
      protein: 18,
      grams: 100,
    },
    {
      ingredient: "Olive Oil",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 100,
      carbohydrates: 0,
      protein: 0,
      grams: 100,
    },
    {
      ingredient: "Butter",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 81,
      carbohydrates: 0.1,
      protein: 0.9,
      grams: 100,
    },
    {
      ingredient: "Mayonnaise",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 75,
      carbohydrates: 0.6,
      protein: 1,
      grams: 100,
    },
    {
      ingredient: "Cream Cheese",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 34,
      carbohydrates: 4,
      protein: 7,
      grams: 100,
    },
    {
      ingredient: "Peanut Butter",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 50,
      carbohydrates: 20,
      protein: 25,
      grams: 100,
    },
    {
      ingredient: "Maple Syrup",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 0,
      carbohydrates: 67,
      protein: 0,
      grams: 100,
    },
    {
      ingredient: "Honey",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 0,
      carbohydrates: 82,
      protein: 0.3,
      grams: 100,
    },
    {
      ingredient: "Soy Sauce",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 0,
      carbohydrates: 5,
      protein: 6,
      grams: 100,
    },
    {
      ingredient: "Ketchup",
      breakdownInTheStomach: 2,
      smallIntestine: 3,
      fats: 0,
      carbohydrates: 25,
      protein: 1,
      grams: 100,
    },
    {
      ingredient: "Mustard",
      breakdownInTheStomach: 2,
      smallIntestine: 3,
      fats: 0.3,
      carbohydrates: 5,
      protein: 1.5,
      grams: 100,
    },
    {
      ingredient: "Barbecue Sauce",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 0,
      carbohydrates: 24,
      protein: 1,
      grams: 100,
    },
    {
      ingredient: "Soy Milk",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 1.8,
      carbohydrates: 3,
      protein: 3.3,
      grams: 100,
    },
    {
      ingredient: "Coconut Milk",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 24,
      carbohydrates: 6,
      protein: 2,
      grams: 100,
    },
    {
      ingredient: "Almond Milk",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 1,
      carbohydrates: 0.2,
      protein: 0.5,
      grams: 100,
    },
    {
      ingredient: "Rice Milk",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 1,
      carbohydrates: 10,
      protein: 0.3,
      grams: 100,
    },
    {
      ingredient: "Apple Juice",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 0.1,
      carbohydrates: 11,
      protein: 0.1,
      grams: 100,
    },
    {
      ingredient: "Orange Juice",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 0.1,
      carbohydrates: 10,
      protein: 0.7,
      grams: 100,
    },
    {
      ingredient: "Tomato Juice",
      breakdownInTheStomach: 2.5,
      smallIntestine: 3.5,
      fats: 0.2,
      carbohydrates: 4,
      protein: 1,
      grams: 100,
    },
    {
      ingredient: "Coffee",
      breakdownInTheStomach: 2,
      smallIntestine: 3,
      fats: 0.1,
      carbohydrates: 0,
      protein: 0.1,
      grams: 100,
    },
    {
      ingredient: "Tea",
      breakdownInTheStomach: 2,
      smallIntestine: 3,
      fats: 0,
      carbohydrates: 0,
      protein: 0,
      grams: 100,
    },
    {
      ingredient: "Beer",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 0,
      carbohydrates: 3.6,
      protein: 0.4,
      grams: 100,
    },
    {
      ingredient: "Wine",
      breakdownInTheStomach: 3,
      smallIntestine: 4,
      fats: 0,
      carbohydrates: 1.7,
      protein: 0.1,
      grams: 100,
    },
    {
      ingredient: "Whiskey",
      breakdownInTheStomach: 4,
      smallIntestine: 5,
      fats: 0,
      carbohydrates: 0,
      protein: 0,
      grams: 100,
    },
  ];
  try {
    
    // Проверка за вече съществуващи ингредиенти
    const existingIngredients = await Ingredient.find({
      ingredient: { $in: dummyData.map(item => item.ingredient) }
    });

    // Извличане на съществуващите имена на ингредиенти
    const existingIngredientNames = existingIngredients.map(item => item.ingredient);

    // Филтриране на новите данни, които не съществуват в базата данни
    const newIngredients = dummyData.filter(item => !existingIngredientNames.includes(item.ingredient));

    // Вмъкване само на новите данни
    if (newIngredients.length > 0) {
      await Ingredient.insertMany(newIngredients);
      console.log("New dummy data added to the database");
    } else {
      console.log("No new dummy data to add");
    }
  } catch (err) {
    console.log("Error adding dummy data:", err);
  }
}
