# Generated by Django 4.2.2 on 2023-09-19 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharitableTrek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('organizers', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='charitable_trek_covers/')),
                ('route_map', models.ImageField(blank=True, null=True, upload_to='charitable_trek_routes/')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrekRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charitable_treks.charitabletrek')),
            ],
        ),
    ]
