# Generated by Django 4.2.2 on 2023-09-09 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charitable_treks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitabletrek',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
