# Generated by Django 4.2.2 on 2023-09-19 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charitable_treks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trekregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charitabletrek',
            name='participants',
            field=models.ManyToManyField(through='charitable_treks.TrekRegistration', to=settings.AUTH_USER_MODEL),
        ),
    ]
