# Generated by Django 4.2.2 on 2024-01-11 19:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CysticFibrosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('How is cystic fibrosis diagnosed?', 'How is cystic fibrosis diagnosed?'), ('How is cystic fibrosis treated?', 'How is cystic fibrosis treated?'), ('How does cystic fibrosis affect the body?', 'How does cystic fibrosis affect the body?'), ('What are the causes of cystic fibrosis?', 'What are the causes of cystic fibrosis?'), ('Frequently Asked Questions?', 'Frequently Asked Questions?'), ('Cystic fibrosis in fiction?', 'Cystic fibrosis in fiction?'), ('Cystic fibrosis for teachers?', 'CF for teachers?'), ('Life with cystic fibrosis?', 'Life with cystic fibrosis?'), ('Hobbies with cystic fibrosis?', 'Hobbies with cystic fibrosis?'), ('Everyday life with cystic fibrosis?', 'Everyday life with cystic fibrosis?'), ('Physical activity with cystic fibrosis?', 'Physical activity with cystic fibrosis?'), ('Optimal nutrition in cystic fibrosis?', 'Optimal nutrition in cystic fibrosis?'), ('Career with cystic fibrosis?', 'Career with cystic fibrosis?'), ('Young people with cystic fibrosis?', 'Young people with cystic fibrosis?'), ('Variety in treatment?', 'Variety in treatment?'), ('Parents and children with cystic fibrosis?', 'Parents and children with cystic fibrosis?'), ('Psychological health with cystic fibrosis?', 'Psychological health with cystic fibrosis?')], max_length=100, unique=True, verbose_name='Title')),
                ('cover_image', models.ImageField(upload_to='donation_covers/', verbose_name='Cover image')),
                ('description', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='donation_covers/', verbose_name='Image')),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
