# Generated by Django 4.2.2 on 2024-01-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystic_fibrosis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cysticfibrosis',
            name='cover_image',
            field=models.ImageField(upload_to='cf_covers/', verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='cysticfibrosis',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cf/', verbose_name='Image'),
        ),
    ]
