# Generated by Django 4.2.2 on 2024-01-13 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystic_fibrosis', '0002_alter_cysticfibrosis_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cysticfibrosis',
            name='eighth_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='eighth_title_of_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='fifth_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='fifth_title_of_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='first_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='First Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='first_title_of_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='First Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='fourth_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='fourth_title_of_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='ninth_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='ninth_title_of_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='picture_of_the_eighth_description',
            field=models.ImageField(blank=True, null=True, upload_to='cf/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='picture_of_the_fifth_description',
            field=models.ImageField(blank=True, null=True, upload_to='cf/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='picture_of_the_first_description',
            field=models.ImageField(blank=True, null=True, upload_to='cf/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='picture_of_the_fourth_description',
            field=models.ImageField(blank=True, null=True, upload_to='cf/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='picture_of_the_ninth_description',
            field=models.ImageField(blank=True, null=True, upload_to='cf/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='picture_of_the_second_description',
            field=models.ImageField(blank=True, null=True, upload_to='cf/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='picture_of_the_seventh_description',
            field=models.ImageField(blank=True, null=True, upload_to='cf/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='picture_of_the_sixth_description',
            field=models.ImageField(blank=True, null=True, upload_to='cf/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='picture_of_the_tenth_description',
            field=models.ImageField(blank=True, null=True, upload_to='cf/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='picture_of_the_third_description',
            field=models.ImageField(blank=True, null=True, upload_to='cf/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='second_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='second_title_of_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='seventh_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='seventh_title_of_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='sixth_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='sixth_title_of_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='tenth_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='tenth_title_of_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='third_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AddField(
            model_name='cysticfibrosis',
            name='third_title_of_description',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Second Title'),
        ),
        migrations.AlterField(
            model_name='cysticfibrosis',
            name='description',
            field=models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Description'),
        ),
    ]
