# Generated by Django 4.2.2 on 2024-01-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cystic_fibrosis', '0004_alter_cysticfibrosis_eighth_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cysticfibrosis',
            name='eighth_description',
        ),
        migrations.RemoveField(
            model_name='cysticfibrosis',
            name='eighth_title_of_description',
        ),
        migrations.RemoveField(
            model_name='cysticfibrosis',
            name='ninth_description',
        ),
        migrations.RemoveField(
            model_name='cysticfibrosis',
            name='ninth_title_of_description',
        ),
        migrations.RemoveField(
            model_name='cysticfibrosis',
            name='picture_of_the_eighth_description',
        ),
        migrations.RemoveField(
            model_name='cysticfibrosis',
            name='picture_of_the_ninth_description',
        ),
        migrations.RemoveField(
            model_name='cysticfibrosis',
            name='picture_of_the_seventh_description',
        ),
        migrations.RemoveField(
            model_name='cysticfibrosis',
            name='picture_of_the_tenth_description',
        ),
        migrations.RemoveField(
            model_name='cysticfibrosis',
            name='seventh_description',
        ),
        migrations.RemoveField(
            model_name='cysticfibrosis',
            name='seventh_title_of_description',
        ),
        migrations.RemoveField(
            model_name='cysticfibrosis',
            name='tenth_description',
        ),
        migrations.RemoveField(
            model_name='cysticfibrosis',
            name='tenth_title_of_description',
        ),
    ]
