# Generated by Django 4.2.2 on 2024-01-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cystic_fibrosis', '0005_remove_cysticfibrosis_eighth_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cysticfibrosis',
            name='picture_of_the_fifth_description',
            field=models.ImageField(blank=True, null=True, upload_to='picture_of_the_fifth_description/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='cysticfibrosis',
            name='picture_of_the_first_description',
            field=models.ImageField(blank=True, null=True, upload_to='picture_of_the_first_description/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='cysticfibrosis',
            name='picture_of_the_fourth_description',
            field=models.ImageField(blank=True, null=True, upload_to='picture_of_the_fourth_description/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='cysticfibrosis',
            name='picture_of_the_second_description',
            field=models.ImageField(blank=True, null=True, upload_to='picture_of_the_second_description/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='cysticfibrosis',
            name='picture_of_the_sixth_description',
            field=models.ImageField(blank=True, null=True, upload_to='picture_of_the_sixth_description/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='cysticfibrosis',
            name='picture_of_the_third_description',
            field=models.ImageField(blank=True, null=True, upload_to='picture_of_the_third_description/', verbose_name='Image'),
        ),
    ]
