# Generated by Django 4.2.4 on 2023-08-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type_user',
            field=models.CharField(blank=True, choices=[('Parent of a patient', 'Parent of a patient'), ('Patient', 'Patient'), ('Donor', 'Donor'), ('Other', 'Other')], max_length=25, null=True, verbose_name='Type user'),
        ),
    ]
