# Generated by Django 4.2.2 on 2023-07-26 14:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import donations.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationAndMedicalEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Name')),
                ('image', models.ImageField(upload_to='photos', validators=[donations.validators.image_size_validator_3mb], verbose_name='Image')),
                ('type', models.CharField(choices=[('Medication', 'Medication'), ('Medical Equipment', 'Medical Equipment')], verbose_name='Type')),
                ('description', models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Description')),
                ('donation_price', models.PositiveIntegerField(verbose_name='Donation Price')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
