# Generated by Django 4.2.2 on 2023-07-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationandmedicalequipment',
            name='image',
            field=models.URLField(verbose_name='Image'),
        ),
    ]
