# Generated by Django 4.2.2 on 2023-07-29 19:15

from django.db import migrations, models
import donations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_medicationandmedicalequipment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationandmedicalequipment',
            name='image',
            field=models.ImageField(upload_to='photos', validators=[donations.validators.image_size_validator_3mb], verbose_name='Image'),
        ),
    ]
