# Generated by Django 4.2.6 on 2023-10-20 14:30

from django.db import migrations, models
import reactjs_frontend_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default='', max_length=400, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile-picture/')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[reactjs_frontend_api.models.phone_validator])),
            ],
        ),
    ]
