# Generated by Django 5.0.1 on 2024-02-13 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(5)])),
                ('category', models.CharField(choices=[('uramaki', 'uramaki'), ('futomaki', 'futomaki'), ('hosomaki', 'hosomaki'), ('nigiri', 'nigiri'), ('sashimi', 'sashimi'), ('poke', 'poke'), ('sets', 'sets'), ('additives', 'additives'), ('salads', 'salads'), ('gioza', 'gioza'), ('noodles', 'noodles'), ('tempura', 'tempura'), ('soup', 'soup'), ('teppanyaki', 'teppanyaki'), ('chicken', 'chicken'), ('pork', 'pork'), ('fish', 'fish'), ('beef', 'beef'), ('garnish', 'garnish'), ('tataki', 'tataki'), ('chirashi', 'chirashi'), ('gunkan', 'gunkan'), ('yakitori', 'yakitori'), ('okonomiyaki', 'okonomiyaki'), ('tonkatsu', 'tonkatsu'), ('sukiyaki', 'sukiyaki'), ('shabu-shabu', 'shabu-shabu'), ('udon', 'udon'), ('soba', 'soba'), ('yakitori', 'yakitori')], max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('ingredients_first', models.CharField()),
                ('ingredients_second', models.CharField()),
                ('ingredients_third', models.CharField()),
                ('ingredients_fourth', models.CharField(blank=True, null=True)),
                ('ingredients_fifth', models.CharField(blank=True, null=True)),
                ('ingredients_sixth', models.CharField(blank=True, null=True)),
                ('ingredients_seventh', models.CharField(blank=True, null=True)),
                ('ingredients_eighth', models.CharField(blank=True, null=True)),
                ('ingredients_ninth', models.CharField(blank=True, null=True)),
                ('ingredients_tenth', models.CharField(blank=True, null=True)),
                ('ingredients_eleventh', models.CharField(blank=True, null=True)),
                ('ingredients_twelfth', models.CharField(blank=True, null=True)),
                ('ingredients_thirteenth', models.CharField(blank=True, null=True)),
                ('ingredients_fourteenth', models.CharField(blank=True, null=True)),
                ('ingredients_fifteenth', models.CharField(blank=True, null=True)),
                ('prep_time', models.CharField()),
                ('cook_time', models.CharField()),
                ('servings', models.CharField(validators=[django.core.validators.MinValueValidator(1)])),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
