# Generated by Django 5.0.1 on 2024-02-25 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('uramaki', 'uramaki'), ('futomaki', 'futomaki'), ('hosomaki', 'hosomaki'), ('nigiri', 'nigiri'), ('sashimi', 'sashimi'), ('poke', 'poke'), ('sets', 'sets'), ('additives', 'additives'), ('salads', 'salads'), ('gioza', 'gioza'), ('noodles', 'noodles'), ('tempura', 'tempura'), ('soup', 'soup'), ('teppanyaki', 'teppanyaki'), ('chicken', 'chicken'), ('pork', 'pork'), ('fish', 'fish'), ('beef', 'beef'), ('garnish', 'garnish'), ('tataki', 'tataki'), ('chirashi', 'chirashi'), ('gunkan', 'gunkan'), ('yakitori', 'yakitori'), ('okonomiyaki', 'okonomiyaki'), ('tonkatsu', 'tonkatsu'), ('sukiyaki', 'sukiyaki'), ('shabu-shabu', 'shabu-shabu'), ('udon', 'udon'), ('soba', 'soba')], max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.CharField(),
        ),
    ]
