# Generated by Django 4.2.2 on 2023-09-19 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Name')),
                ('image', models.ImageField(upload_to='donation_covers/', verbose_name='Image')),
                ('type', models.CharField(choices=[('Support for research', 'Support for research'), ('Psychological support', 'Psychological support'), ('Medication', 'Medication'), ('Medical Equipment', 'Medical Equipment'), ('Another type of donation', 'Another type of donation')], verbose_name='Type')),
                ('description', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Description')),
                ('donation_price', models.PositiveIntegerField(verbose_name='Donation Price')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
