# Generated by Django 4.2.4 on 2023-08-18 12:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Donation Amount')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Name')),
                ('image', models.ImageField(upload_to='donation_covers/', verbose_name='Image')),
                ('type', models.CharField(choices=[('Support for research', 'Support for research'), ('Psychological support', 'Psychological support'), ('Medication', 'Medication'), ('Medical Equipment', 'Medical Equipment'), ('Another type of donation', 'Another type of donation')], verbose_name='Type')),
                ('description', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Description')),
                ('donation_price', models.PositiveIntegerField(verbose_name='Donation Price')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
