# Generated by Django 4.2.2 on 2023-09-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneydonation',
            old_name='user',
            new_name='creator',
        ),
    ]
