# Generated by Django 4.2.2 on 2023-09-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_rename_user_moneydonation_creator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoneyDonation',
        ),
    ]
