# Generated by Django 4.2.2 on 2023-09-19 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(5)])),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='benefactor_covers/')),
                ('total_donations', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
