# Generated by Django 4.2.2 on 2023-09-27 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='campaign_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
