# Generated by Django 4.2.4 on 2023-08-31 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='money',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donations.moneydonation'),
            preserve_default=False,
        ),
    ]
