# Generated by Django 4.2.2 on 2023-09-09 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('cart', '0004_alter_cartitem_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='money',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.moneydonation'),
        ),
    ]
