# Generated by Django 4.2.2 on 2023-09-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='money',
        ),
    ]
